### ISSUE TITLE
Any interest in helping write something to strip out fingerprints from text?

### ISSUE THREAD

**Issue by nitrocode** [analyticascent/stylext#1]
Great write up.

I've looked into [feature-9](https://events.ccc.de/congress/2011/Fahrplan/attachments/2019_28C3-authorship.pdf) and anonymouth and noticed there are surprisingly limited apps that can anonymize text. I'd like it to work using:

* command line
* browser extensions
    * maybe something that grabs input in textareas and input fields and removes uniqueness in text before it's submitted
* git commit messages
    * perhaps a prehook that calls the command line mention
* code - function names, comments, etc
* etc

Would you be interested in helping me write an app like that?

**Comment by analyticascent** [comment]
Hello nitrocode,

I would love to pursue that as an end goal and it looks like you have noticed the same things I have about existing apps.

The difference between what those do and what Stylext currently does is that to make Stylext capable of disguising unique elements of someone's writing, it would have to take an _unsupervised_ machine learning approach to "detect" what would distinguish one person's writing from someone else's.

Some feature engineering would have to be involved to see what elements to look for (average syllables per sentence, common n-grams, etc).

A command line tool would be easy to do (just paste in sample text and output what's distinct about it compared to a large body of other writing samples), a browser extension could easily come next.

Are you on Keybase?

**Comment by farrp2011** [comment]
>>nitrocode

Write a detailed description of how to anonymize text.  If I wanted to anonymize text, I would throw it into google translate.  Translate it into a language that is very different form English and translate it back.

**Comment by analyticascent** [comment]
> If I wanted to anonymize text, I would throw it into google translate.

That method has been tested before and found to be _somewhat_ unreliable. [What Drexel University researchers found](https://www.cs.drexel.edu/~sa499/papers/adversarial_stylometry.pdf) was that translation tools end up reverting right back to a sentence that's roughly identical to what you started with.

Contractions (it's vs it is for instance) and wording may differ slightly, but _syllable count per sentence and writer invariants_ (such as unique vocabulary words that have few synonyms when translated) can still serve as giveaways when analyzed. **Also keep in mind that Google translate almost always outputs contractions where possible, so if you already used those to begin with the original writing style won't be changed.**

That's not to say that the approach is useless, just that it can't be relied upon _by itself_. It may be useful for doing a bulk transformation of a large body of text (say, an entire blog post) but you still have to keep in mind that many style invariants survive that translation process.

As far as I understand things, an obfuscation approach that modifies just a handful of potential invariants (n-grams, choice of synonyms, average syllable count per sentence, etc) can sufficiently provide a layer of plausible deniability.

**This may sound like a sketchy approach, but I think the easiest way to go is to find some sample text from someone who's written about the same thing you're talking about and mimic their style somewhat.**

I'll go into further detail about all this soon in a new markdown file for the Stylext repo. It will be a way for people to get up to speed on what the existing research has found about both stylometry and obfuscation so they can get to coding quicker.

I really do like the idea of a command line tool and eventually browser add-on; the tools that the team at Drexel put together are effective but extremely hard to use for those that have never installed Eclipse before in their life. My intent for starting this project was to rely on a more accessible programming language (to make things easy for devs) but also to reduce the hurdles for those that want to actually use stylometry and/or obfuscation techniques, so anyone interested is more than welcome to give suggestions on this.

**I'm checking my repos and updating them more frequently now so if either of you have any questions feel free to drop me a line here.**

**Comment by farrp2011** [comment]
Okay some elements that we need to change are contractions, simplifying synonyms and syllable count per sentence.  All those thing would be easy to change.  N-grams would the hard part.  How I would come at n-grams is to break it up into 2 sentences.

**Comment by analyticascent** [comment]
Not only are n-grams the hard part, they are likely the most important giveaway.

Distinct n-grams can be detected, but it's ultimately up to the writer how they want to disguise that. I guess the goal would be to have them keep changing their style based on suggestions until the accuracy score of linking their normal writing with the new writing they want to disguise goes down.

**Comment by analyticascent** [comment]
I'll close this thread for now; currently updating the repo so it's Anaconda Python 3 ready out of the box.

I do plan on getting in touch with each of you once I begin the process of extending it to obfuscate writing styles in addition to it's current authorship attribution function. All we really have to do is decide on a list of features that could overlap with writer invariants and try out various unsupervised machine learning algorithms to see how well we can generate obfuscation recommendations.

Stay tuned

**Comment by nitrocode** [comment]
Hmm I like the idea of google translate and expanding contractions. Could use the GNU model where each item in the anonmyzation chain is its own command line utility.

For instance:

```
cat text-to-anonymize.txt | \
      google-translate to chinese | \
      google-translate to english | \
      expand-contractions | \
      decrease-word-syllables --max=3 | \
      etc
```

Also, apologies for flaking on this. I sent you a message on keybase.
